In [1]:
import torch
a=[13.5,12.5,11.5]
a=torch.tensor(a)
a.round()



tensor([14., 12., 12.])

In [2]:
torch.tensor([-2.5000 , -1.5000,   -0.5000,    0.5000 ,   1.5000  ,  2.5000]).round()

tensor([-2., -2., -0.,  0.,  2.,  2.])

In [11]:
X=torch.tensor([[[1,2,3,4],[1,2,3,4]],[[1,2,3,4],[1,2,3,4]]])
Y=torch.tensor([1,2,3,4])
X*Y

tensor([[[ 1,  4,  9, 16],
         [ 1,  4,  9, 16]],

        [[ 1,  4,  9, 16],
         [ 1,  4,  9, 16]]])